language: groovy

jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=256m -XX:PermSize=256m"

script:
  - ./gradlew clean build check uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew cobertura coveralls --full-stacktrace
