language: groovy

jdk:
  - openjdk7
  - oraclejdk8

script:
  - ./gradlew clean build check uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew cobertura coveralls --full-stacktrace
