language: groovy

jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=512m -XX:PermSize=256m"

script:
  - ulimit -a
  - ulimit -s 1082768
  - ulimit -a
  - ./gradlew clean build uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew coveralls --full-stacktrace
