language: groovy

jdk:
  - openjdk7
  - oraclejdk8

script:
  - ./gradlew clean build check uploadArchives
  - cd samples/example && ./gradlew clean webResourceCompile && cd ..

after_success:
  - ./gradlew cobertura coveralls
