language: groovy

jdk:
  - openjdk7
  - oraclejdk8

env:
  global:
  - GRADLE_OPTS="-Xmx1536m"

script:
  - ./gradlew clean build uploadArchives --full-stacktrace
  - cd samples/example && ./gradlew clean webResourceCompile --full-stacktrace && cd ../../

after_success:
  - ./gradlew coveralls --full-stacktrace
