version: "{build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat --full-stacktrace clean assemble

test_script:
  - gradlew.bat --full-stacktrace check
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
